source 'https://rubygems.org'

gem "webrick", "~> 1.7"
gem "grpc", "~> 1.64" # HACKED: gRPC runtime for details service
gem "grpc-tools", "~> 1.64" # HACKED: gRPC codegen for details proto
gem "grpc-reflection", "~> 1.64" # HACKED: for grpcurl/grpc_cli support
